/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Story = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : Time,
  'authorId' : IDL.Text,
  'createdAt' : Time,
  'text' : IDL.Opt(IDL.Text),
  'imageBlobId' : ExternalBlob,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'deliveryAddress' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : Time,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(CartItem),
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'postType' : IDL.Variant({ 'post' : IDL.Null, 'reel' : IDL.Null }),
  'authorId' : IDL.Text,
  'createdAt' : Time,
  'trendingScore' : IDL.Float64,
  'approvalStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'shareCount' : IDL.Nat,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'imageBlobId' : IDL.Opt(ExternalBlob),
  'textContent' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'sellerId' : IDL.Text,
  'price' : IDL.Float64,
  'imageBlobId' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'isCreator' : IDL.Bool,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'avatarBlobId' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Text,
  'createdAt' : Time,
  'text' : IDL.Text,
  'postId' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : IDL.Variant({
    'subscribe' : IDL.Null,
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'follow' : IDL.Null,
  }),
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'actorId' : IDL.Text,
  'recipientId' : IDL.Text,
  'postId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'approvePost' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNotification' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'subscribe' : IDL.Null,
          'like' : IDL.Null,
          'comment' : IDL.Null,
          'follow' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Text], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'post' : IDL.Null, 'reel' : IDL.Null })],
      [],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createStory' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text), Time], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Text], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCreatorEarnings' : IDL.Func([], [IDL.Float64], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getFollowings' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFriendSuggestions' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPendingPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'postCount' : IDL.Nat,
          'orderCount' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPostComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getSubscriberCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTotalCommissions' : IDL.Func([], [IDL.Float64], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribedToCreator' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'markStoryViewed' : IDL.Func([IDL.Text], [], []),
  'rejectPost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribeToCreator' : IDL.Func([IDL.Text], [], []),
  'toggleCreatorStatus' : IDL.Func([], [], []),
  'toggleUserActiveStatus' : IDL.Func([IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Text], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'unsubscribeFromCreator' : IDL.Func([IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Story = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : Time,
    'authorId' : IDL.Text,
    'createdAt' : Time,
    'text' : IDL.Opt(IDL.Text),
    'imageBlobId' : ExternalBlob,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'deliveryAddress' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : Time,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(CartItem),
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'postType' : IDL.Variant({ 'post' : IDL.Null, 'reel' : IDL.Null }),
    'authorId' : IDL.Text,
    'createdAt' : Time,
    'trendingScore' : IDL.Float64,
    'approvalStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'shareCount' : IDL.Nat,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'imageBlobId' : IDL.Opt(ExternalBlob),
    'textContent' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'sellerId' : IDL.Text,
    'price' : IDL.Float64,
    'imageBlobId' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'isCreator' : IDL.Bool,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'avatarBlobId' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Text,
    'createdAt' : Time,
    'text' : IDL.Text,
    'postId' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : IDL.Variant({
      'subscribe' : IDL.Null,
      'like' : IDL.Null,
      'comment' : IDL.Null,
      'follow' : IDL.Null,
    }),
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'actorId' : IDL.Text,
    'recipientId' : IDL.Text,
    'postId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approvePost' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNotification' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'subscribe' : IDL.Null,
            'like' : IDL.Null,
            'comment' : IDL.Null,
            'follow' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createOrder' : IDL.Func([IDL.Text], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'post' : IDL.Null, 'reel' : IDL.Null })],
        [],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createStory' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text), Time], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Text], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCreatorEarnings' : IDL.Func([], [IDL.Float64], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowingCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getFollowings' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFriendSuggestions' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPendingPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'postCount' : IDL.Nat,
            'orderCount' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPostComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSubscriberCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTotalCommissions' : IDL.Func([], [IDL.Float64], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserPosts' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribedToCreator' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'markStoryViewed' : IDL.Func([IDL.Text], [], []),
    'rejectPost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribeToCreator' : IDL.Func([IDL.Text], [], []),
    'toggleCreatorStatus' : IDL.Func([], [], []),
    'toggleUserActiveStatus' : IDL.Func([IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Text], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'unsubscribeFromCreator' : IDL.Func([IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };