/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface Comment {
  'id' : string,
  'authorId' : string,
  'createdAt' : Time,
  'text' : string,
  'postId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Notification {
  'id' : string,
  'notificationType' : { 'subscribe' : null } |
    { 'like' : null } |
    { 'comment' : null } |
    { 'follow' : null },
  'createdAt' : Time,
  'isRead' : boolean,
  'actorId' : string,
  'recipientId' : string,
  'postId' : [] | [string],
}
export interface Order {
  'id' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'completed' : null },
  'deliveryAddress' : string,
  'userId' : string,
  'createdAt' : Time,
  'totalAmount' : number,
  'items' : Array<CartItem>,
}
export interface Post {
  'id' : string,
  'postType' : { 'post' : null } |
    { 'reel' : null },
  'authorId' : string,
  'createdAt' : Time,
  'trendingScore' : number,
  'approvalStatus' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'shareCount' : bigint,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'imageBlobId' : [] | [ExternalBlob],
  'textContent' : string,
}
export interface Product {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'stock' : bigint,
  'category' : string,
  'sellerId' : string,
  'price' : number,
  'imageBlobId' : [] | [ExternalBlob],
}
export interface Story {
  'id' : string,
  'expiresAt' : Time,
  'authorId' : string,
  'createdAt' : Time,
  'text' : [] | [string],
  'imageBlobId' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile {
  'id' : string,
  'bio' : string,
  'isCreator' : boolean,
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'avatarBlobId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'approvePost' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNotification' : ActorMethod<
    [
      string,
      { 'subscribe' : null } |
        { 'like' : null } |
        { 'comment' : null } |
        { 'follow' : null },
      [] | [string],
    ],
    undefined
  >,
  'createOrder' : ActorMethod<[string], undefined>,
  'createPost' : ActorMethod<
    [string, { 'post' : null } | { 'reel' : null }],
    undefined
  >,
  'createProduct' : ActorMethod<
    [string, string, number, string, bigint],
    undefined
  >,
  'createStory' : ActorMethod<[ExternalBlob, [] | [string], Time], undefined>,
  'createUserProfile' : ActorMethod<[string, string, string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[string], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCreatorEarnings' : ActorMethod<[], number>,
  'getFollowerCount' : ActorMethod<[string], bigint>,
  'getFollowers' : ActorMethod<[string], Array<string>>,
  'getFollowingCount' : ActorMethod<[string], bigint>,
  'getFollowings' : ActorMethod<[string], Array<string>>,
  'getFriendSuggestions' : ActorMethod<[], Array<UserProfile>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getPendingPosts' : ActorMethod<[], Array<Post>>,
  'getPlatformStats' : ActorMethod<
    [],
    { 'postCount' : bigint, 'orderCount' : bigint, 'userCount' : bigint }
  >,
  'getPostComments' : ActorMethod<[string], Array<Comment>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getSubscriberCount' : ActorMethod<[string], bigint>,
  'getTotalCommissions' : ActorMethod<[], number>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserPosts' : ActorMethod<[string], Array<Post>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribedToCreator' : ActorMethod<[string], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'markStoryViewed' : ActorMethod<[string], undefined>,
  'rejectPost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeToCreator' : ActorMethod<[string], undefined>,
  'toggleCreatorStatus' : ActorMethod<[], undefined>,
  'toggleUserActiveStatus' : ActorMethod<[string], undefined>,
  'unfollowUser' : ActorMethod<[string], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'unsubscribeFromCreator' : ActorMethod<[string], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, number, string, bigint],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];